apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "rpetemplate-product-infrastructure"
  description: test-4
spec:
  type: service
  lifecycle: experimental
  owner: praveen.adusumilli
